// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VrBook.Modules.Sync.Infrastructure.Persistence;

#nullable disable

namespace VrBook.Modules.Sync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260627011530_OpsM3a_Sync_TenantIdColumn")]
    partial class OpsM3a_Sync_TenantIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sync")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VrBook.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("ix_outbox_messages_dispatched_at");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("outbox_messages", "sync");
                });

            modelBuilder.Entity("VrBook.Modules.Sync.Domain.ChannelFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ETag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("etag");

                    b.Property<string>("InboundUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("inbound_url");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("OutboundToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("outbound_token");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("poll_interval_minutes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OutboundToken")
                        .IsUnique();

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("IsEnabled", "LastAttemptAt")
                        .HasDatabaseName("ix_channel_feeds_due_for_poll");

                    b.ToTable("channel_feeds", "sync");
                });

            modelBuilder.Entity("VrBook.Modules.Sync.Domain.ExternalReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<Guid>("ChannelFeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_feed_id");

                    b.Property<DateOnly>("Checkin")
                        .HasColumnType("date")
                        .HasColumnName("checkin");

                    b.Property<DateOnly>("Checkout")
                        .HasColumnType("date")
                        .HasColumnName("checkout");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ICalUid")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ical_uid");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ChannelFeedId", "ICalUid")
                        .IsUnique()
                        .HasDatabaseName("ix_external_reservations_feed_uid");

                    b.HasIndex("PropertyId", "CancelledAt", "Checkin", "Checkout")
                        .HasDatabaseName("ix_external_reservations_overlap");

                    b.ToTable("external_reservations", "sync");
                });

            modelBuilder.Entity("VrBook.Modules.Sync.Domain.SyncConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("ExternalReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_reservation_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Resolution")
                        .HasColumnType("integer")
                        .HasColumnName("resolution");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("BookingId", "ExternalReservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_sync_conflicts_booking_external_pending")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("PropertyId", "Resolution")
                        .HasDatabaseName("ix_sync_conflicts_property_resolution");

                    b.ToTable("sync_conflicts", "sync");
                });

            modelBuilder.Entity("VrBook.Modules.Sync.Domain.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<Guid>("ChannelFeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_feed_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("EventsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("events_cancelled");

                    b.Property<int>("EventsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("events_new");

                    b.Property<int>("EventsSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("events_seen");

                    b.Property<int>("EventsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("events_updated");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ChannelFeedId", "StartedAt")
                        .HasDatabaseName("ix_sync_runs_feed_started");

                    b.ToTable("sync_runs", "sync");
                });
#pragma warning restore 612, 618
        }
    }
}
